---
- name: Install node.js and npm
  hosts: ubuntu
  become: yes
  tasks:
  - name: Update apt repo and cache 
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600
  - name: Install node.js and npm
    apt:
      pkg:
      - nodejs
      - npm

- name: Deploy nodejs application
  hosts: ubuntu
  become: yes
  tasks:  
  - name: Unpacked the nodejs tar file 
    unarchive:
      src: ./simple-nodejs.tar.gz
      dest: /opt/

       
  

