---
- name: Install node.js and npm
  hosts: ubuntu
  become: yes
  tasks:
  - name: Update apt repo and cache 
    apt:
      update_cache: true
      force_apt_get: true
      cache_valid_time: 3600
  - name: Install node.js and npm
    apt:
      pkg:
      - nodejs
      - npm

- name: Deploy nodejs application
  hosts: ubuntu
  become: yes
  tasks:  
  - name: Unpacked the nodejs tar file 
    unarchive:
      src: ./simple-nodejs.tar.gz
      dest: /opt/
  - name: Install dependencies
    npm:
      path: /opt/simple-nodejs
  - name: Start the application
    command:
      chdir: /opt/simple-nodejs/app
      cmd: node server
    async: 100
    poll: 0
  - name: Ensure application is running
    shell: ps aux | grep node 
    register: app_status
  - name: Print application status
    debug: msg={{ app_status.stdout_lines }}







 
       
  

